name: .NET Build v2

on:
  push:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup msbuild
      uses: microsoft/setup-msbuild@v1.3.1
      
    - name: Restore dependencies
      run: msbuild -t:restore
      
    - name: Setup NuGet.exe
      uses: nuget/setup-nuget@v1
      with:
        nuget-version: latest 
        
    - name: Restore Nuget Dependencies
      run: nuget restore ModAssistant.sln
    
    - name: Build project
      run: msbuild ModAssistant/ModAssistant.csproj /t:Build /p:Configuration=Release
      
    - name: Cleanup release
      shell: bash
      run: |
        find "ModAssistant/bin/Release" -type f ! -name "ModAssistant.exe" -delete
        cp "LICENSE" "ModAssistant/bin/Release/LICENSE.ModAssistant.txt"
    - name: Upload Build
      if: startsWith(github.ref, 'refs/tags/') == false
      uses: actions/upload-artifact@v3
      with:
        name: ModAssistant-${{ github.sha }}
        path: ./ModAssistant/bin/Release/
        
    - name: Extract Release Version
      if: startsWith(github.ref, 'refs/tags/')
      id: get_version
      shell: bash
      run: echo "version=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT
      
    - name: Release
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        name: Mod Assistant v${{ steps.get_version.outputs.version }}
        files: ./ModAssistant/bin/Release/ModAssistant.exe